image:
  file: .gitpod.Dockerfile

tasks:
  - name: Enable Corepack and Install Frontend Dependencies
    init: |
      corepack enable
      cd frontend && yarn install
  - name: Install Microservice 1 Frontend Dependencies
    init: |
      cd micro/service1/frontend && yarn install
  - name: Install Backend Dependencies
    init: |
      cd micro/service1/backend && pip install -r requirements.txt

  - name: Start Main Frontend (Vite)
    command: cd frontend && yarn dev

  - name: Start Microservice 1 Frontend
    command: cd micro/service1/frontend && yarn dev

  - name: Start Backend
    command: cd micro/service1/backend && python manage.py runserver 0.0.0.0:8000

ports:
  - port: 3000
    onOpen: open-preview
    name: Main Frontend
  - port: 3001
    onOpen: open-preview
    name: Microservice 1 Frontend
  - port: 8000
    onOpen: open-preview
    name: Backend
