image:
  file: .gitpod.Dockerfile

tasks:
  - init: pip install nemo_toolkit[all] torch
  - init: npm install -g tailwindcss
  - command: uvicorn main:app --host 0.0.0.0 --port 8000

ports:
  - port: 8000
    onOpen: open-preview

