version: "3.8"

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: microservice1_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user"]
      interval: 10s
      retries: 5
      timeout: 5s

  service1_backend:
    build:
      context: ./micro/service1/server  # Path to the backend Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_NAME: microservice1_db
      DATABASE_USER: user
      DATABASE_PASSWORD: password123
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      GITPOD_WORKSPACE_URL: ${GITPOD_WORKSPACE_URL}
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8000"

  service1_frontend:
    build:
      context: ./micro/service1/frontend  # Path to the frontend Dockerfile
    command: yarn dev
    ports:
      - "3001"

  main_frontend:
    build:
      context: ./frontend  # Path to the main frontend Dockerfile
    command: yarn dev
    ports:
      - "3000"

volumes:
  postgres_data:
