# Use the official Node.js image
FROM node:18

# Set the working directory in the container
WORKDIR /app

# Copy the package.json and package-lock.json files
COPY frontend/package*.json ./

# Install frontend dependencies
RUN npm install
ENV PATH="./node_modules/.bin:$PATH"


# Copy the frontend source code into the container
COPY frontend/ ./

# Expose the port that the frontend listens on
EXPOSE 3000

# Command to run the frontend development server
CMD ["npm", "run", "dev"]
